//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using UtilsLibrary;

    public partial class User
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string StateProvinceName { get; set; }
        public string CountryRegionName { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> HomeOwnerFlag { get; set; }
        public Nullable<int> NumberCarsOwned { get; set; }
        public Nullable<int> NumberChildrenAtHome { get; set; }
        public Nullable<int> TotalChildren { get; set; }
        public Nullable<int> YearlyIncome { get; set; }

        public string GetUserInfo()
        {
            return "USER INFORMATION: " + "\n" +
                   this.Id + "\n" + this.Title + "\n" + this.FirstName + "\n" + this.MiddleName + "\n" + this.LastName + "\n" + this.Suffix + "\n" +
                   this.AddressLine1 + "\n" + this.AddressLine2 + "\n" + this.City + "\n" + this.StateProvinceName + "\n" + this.CountryRegionName + "\n" +
                   this.PostalCode + "\n" + this.PhoneNumber + "\n" + DateUtils.ToUTC(BirthDate.Value) + "\n" + this.Education + "\n" + this.Occupation + "\n" + 
                   this.Gender + "\n" + this.MaritalStatus + "\n" + this.HomeOwnerFlag + "\n" + this.NumberCarsOwned + "\n" + this.NumberChildrenAtHome + "\n" + 
                   this.TotalChildren + "\n" + this.YearlyIncome;
        }
    }
}
